version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - sbanet
    environment:
      - JAVA_OPTS= -Xms128m -Xmx256m
    mem_limit: 256m
    cpus: 0.25

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sbanet
    mem_limit: 256m
    cpus: 0.25
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - sbanet
    mem_limit: 256m
    cpus: 0.25
networks:
  sbanet:
    external: true